spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imaginnovatedb?useSSL=false
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    basename: language/response
  boot:
    exception:
      trace: true